name: MongoDb Backup
description: Makes mongodump backup 
inputs:
  connection-string:
    description: connection string from mongo
    required: true
  username:
    required: true

outputs:
  binary-backup:
    description: binary backup as artifact

runs:
  using: node16
  main: index.js
